version: '3'

services:
  xuinew:
    container_name: xuinewadmin
    image: neikuwaichuan/v2-admin:25.0
    restart: always
    ports:
      - "80:80"
      - "181:181"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/app/config
      - ./temp:/app/temp
      - ./dist:/app/static/dist
      - ./v2-admin:/app/v2-admin
      - ./agentInstall:/app/agentInstall
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - xuinew

  mysql:
    image: mysql:8.0
    restart: always
    container_name: xuinewdb
    command: --skip-log-bin --expire-logs-days=7 --max-binlog-size=104857600
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: x-ui-new
      MYSQL_USER: xuinewdb
      MYSQL_PASSWORD: 123456
    volumes:
      - ./x-ui-new.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - xuinew

  redis:
    image: redis:latest
    restart: always
    container_name: xuinewredis
    networks:
      - xuinew
networks:
  xuinew:
